#' Calculate the expected proportion of transmission from a given proportion of infectious cases.
#'
#' @description Calculates the expected proportion of transmission from a given proportion of infectious cases. This is an alternative but  distinct formulation to the function `proportion_transmission()`. 
#' 
#' `proportion_transmission()` calculates relative transmission heterogeneity from the offspring distribution of secondary cases, Z, where the upper proportion of the distribution comprise x% of total number of cases given R0 and k, where x is typically defined as 0.8 or 80%. e.g. 80% of all transmissions are generated by the upper 20% of cases, or p_80 = 0.2, per the 80/20 rule. In this formulation, changes in R can have a significant effect on the estimate of p_80 even when k is constant. Importantly, this formulation DOES NOT allow for true homogeneity when k = InF i.e. p_80 = 0.8.
#' 
#' 
#' `proportion_transmission2()` calculates a similar ratio, instead in terms of the theoretical invididual reproductive number and infectiousness given R0 and k. The individual reproductive number, 'v', is described in Lloyd-Smith JO et al. 2005, "as a random variable representing the expected number of secondary cases caused by a particular infected individual. Values for v are drawn from a continuous gamma probability distribution with population mean R0 [and dispersion paramter k], which encodes all variation in infectious histories of individuals, including properties of the host and pathogen and environmental circumstances."
#' 
#' For `proportion_transmission2()`, we define the upper proportion of infectiousness, which is typically 0.2 i.e. the upper 20% most infectious cases, again per the 80/20 rule. e.g. the most infectious 20% of cases, are expected to produce 80% of all infections, or t_20 = 0.8. Unlike `proportion_transmission()`, changes in R have no effect on the estimate of t_80 when k is constant, but R is still required for the underlying calculation. This formulation DOES allow for true homogeneity when k = InF i.e. t_20 = 0.2, or t_80 = 0.8.
#' 
#' The original code is from ongoing work originating from https://github.com/dcadam/kt and:
#'
#' Adam D, Gostic K, Tsang T, Wu P, Lim WW, Yeung A, et al. 
#' Time-varying transmission heterogeneity of SARS and COVID-19 in Hong Kong. 2022.
#' 10.21203/rs.3.rs-1407962/v1
#' 
#' Following the formula defined in section 2.2.5 of the supplementary material for:
#'
#' Lloyd-Smith JO, Schreiber SJ, Kopp PE, Getz WM. Superspreading and the effect of
#' individual variation on disease emergence. Nature. 2005 Nov;438(7066):355–9.
#' 10.1038/nature04153
#' 

#### FUNCTIONS

### Defines the gamma density function in terms of the mean reproductive number (R) and the dispersion paramter (k)
dgammaRk <- function(x, R, k) {
  out <- dgamma(x, shape = k, scale = R / k)
  return(out)
}

### Defines the gamma distribution function in terms of the mean reproductive number (R) and the dispersion paramter (k)
pgammaRk <- function(x, R, k) {
  out <- pgamma(x, shape = k, scale = R / k)
  return(out)
}

### Generates a log scaled sequence of real numbers (useful for plotting later)
lseq <- function(from, to, length.out) {
  exp(seq(log(from), log(to), length.out = length.out))
}

### Gamma probability densitiy function (pdf) describing the individual reproductive number ν given R0 and k 
fvx <- function(x, R, k) {
  dgammaRk(x = x, R = R, k = k)
}

### Unitroot solver for the solution to u, or the value of x from the gamma CDF given the desired proportion of transmission.
solve_for_u <- function(prop, R, k) {
  
  f <- function(x, prop) {
    res <- 1 - pgammaRk(x, R, k)
    res - prop
  }
  
  # Initial interval for u
  lower <- 0
  upper <- 1
  
  # Find the root using uniroot
  root <- uniroot(f, prop = prop, interval = c(lower, upper), extendInt="yes")
    
  root$root
  
}

### Function: Calculates the expected proportion of transmission from the upper 'prop'% of most infectious cases
proportion_transmission2 <- function(R, k, prop) {

  u <- solve_for_u(prop = prop, R = R, k = k)

  integral_result <- integrate(function(u) u * fvx(u, R, k), lower = 0, upper = u)
  
  res <- integral_result$value / R
  
  1 - res
  
}

### Test: Given R0 = 3 and k = 1, the upper 20% most infectious individuals are expected to produce 52% of all transmissions
proportion_transmission2(R = 3, k = 1, prop = 0.2)

### Test: Given R0 = 2 and k = Inf, the upper 20% most infectious individuals are expected to produce 20% of all transmissions i.e. no heterogeneity.
proportion_transmission2(R = 2, k = 10e5, prop = 0.2)


### PLOTTING. It is possible to visualise the expected proportion of transmisison by vectorising a sequence of infectiousnes per fig.1b of Lloyd-Smith JO et al. 2005. This is still in active developement and wont work for all inputs of R and k. 

x <- seq(from = 0, to = 1, by = 0.01)
y <- purrr::map_dbl(x, function(x) proportion_transmission2(R = 2, k = 1, prop = x))

library(ggplot2)

data.table::data.table(x, y) |> 
  ggplot() +
  geom_line(mapping = aes(x = x, y = y)) +
  geom_abline(slope = 1, linetype = 2, alpha = 0.2) +
  geom_vline(xintercept = 0.2, linetype = 2, alpha = 0.2) + # the yintercept when x = 0.2 is the value of t_20 = 0.52
  theme_classic() +
  theme(aspect.ratio = 1) +
  annotate(geom = "text",
  angle = 45, 
  size = 2.5, 
  x = 0.5,
  y = 0.5,
  vjust = 1.5,
  label = "Homogeneous population") +
  labs(x = "Proportion of infectious cases (ranked)",
        y = "Expected proportion of transmission") +
  coord_cartesian(expand = FALSE)

### Alternatively we can also see the distribution of t_20 given k per fig.1b of Lloyd-Smith JO et al. 2005. 

k_seq <- lseq(from = 0.01, to = 100, length.out = 1000)
y <- purrr::map_dbl(k_seq, function(x) proportion_transmission2(R = 2, k = x, prop = 0.2))


addline_format <- function(x,...){
  gsub('\\s','\n',x)
}

data.table::data.table(k_seq, y) |> 
  ggplot() +
  geom_line(mapping = aes(x = k_seq, y = y)) + 
  geom_hline(yintercept = c(0.2, 0.8), linetype = 2, alpha = 0.2) +
  theme_classic() +
  theme(aspect.ratio = 1) +
  scale_y_continuous(name = c("Proportion of transmission expected from\nthe most infectious 20% of cases (t20)"), 
    limits = c(0,1)) +
  scale_x_log10(name = "Dispersion paramter (k)", expand = c(0,0))
